apiVersion: v1
kind: Service
metadata:
  name: ghost
  namespace: ghost-blog
spec:
  type: ClusterIP
  selector:
    app: ghost
  ports:
    - name: ghost-service
      port: 2368
      targetPort: 2368
      protocol: TCP
