apiVersion: batch/v1
kind: CronJob
metadata:
  name: ghost-mysql-hourly-backup
  namespace: ghost-blog
spec:
  schedule: "0 * * * *"  # Runs every hour at minute 0
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: mysql-backup
            image: mysql:5.7
            command: ["/bin/sh", "-c"]
            args:
              - |
                # Set timestamp
                TIMESTAMP=$(date +%Y-%m-%d_%H-%M)
                
                # Create backup
                mysqldump -h mysql -u root -p$(MYSQL_ROOT_PASSWORD) ghostdb | gzip > /backups/hourly/ghost_backup_${TIMESTAMP}.sql.gz
                
                # Keep only last 24 hourly backups
                ls -t /backups/hourly/ghost_backup_*.sql.gz | tail -n +25 | xargs rm -f --
                
                echo "Backup completed at $(date)"
            env:
              - name: MYSQL_ROOT_PASSWORD
                valueFrom:
                  secretKeyRef:
                    name: mysql-secret
                    key: mysql-root-password
            volumeMounts:
              - name: backup-storage
                mountPath: /backups
          restartPolicy: OnFailure
          volumes:
            - name: backup-storage
              persistentVolumeClaim:
                claimName: mysql-backup-pvc  # Change to your PVC
