apiVersion: v1
kind: Service
metadata:
  name: ghost
  namespace: ghost-blog
spec:
  selector:
    app: ghost
  ports:
    - name: https
      protocol: TCP
      port: 443            # Expose port 80 to ALB
      targetPort: 2368    # Internally forward to Ghost's port
  type: ClusterIP
