apiVersion: v1
kind: Service
metadata:
  name: ghost
  namespace: ghost-blog
spec:
  type: LoadBalancer
  selector:
    app: ghost
  ports:
    - name: https
      port: 443          # External HTTPS port
      targetPort: 2368   # Internal Ghost app port
      protocol: TCP
