apiVersion: v1
kind: Service
metadata:
  name: ghost
  namespace: ghost-blog
spec:
  selector:
    app: ghost
  ports:
    - name: http
      port: 80
      targetPort: 2368
      protocol: TCP
  type: ClusterIP
