apiVersion: v1
kind: Service
metadata:
  name: ghost
  namespace: ghost-blog
  labels:
    app: ghost
spec:
  selector:
    app: ghost  # Ensure your Ghost Deployment has this label
  ports:
    - name: http
      port: 80            # Port exposed to Ingress (ALB)
      targetPort: 2368    # Actual port used by Ghost container
      protocol: TCP
  type: ClusterIP
