apiVersion: v1
kind: Service
metadata:
  name: ghost
  namespace: ghost-blog
  labels:
    app: ghost
    argocd.argoproj.io/instance: ghost
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-scheme: internet-facing
    service.beta.kubernetes.io/aws-load-balancer-type: nlb
spec:
  type: LoadBalancer
  selector:
    app: ghost
  ports:
    - protocol: TCP
      port: 80
      targetPort: 2368
