apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: ghost-blog
  labels:
    app: mysql
spec:
  selector:
    app: mysql
  type: ClusterIP
  ports:
    - name: mysql
      port: 3306
      targetPort: 3306
